
[agent]
  interval = "3s"
  round_interval = false
  metric_batch_size = 50
  metric_buffer_limit =500
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  hostname = ""
  omit_hostname = false
# Read metrics from MQTT topic(s)
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  
  ## Topics that will be subscribed to.
  topics = [
    "Simcofi/Guatemala/Camara1/telemetry/#"
    
  ]  
  topic_tag = "topic"

  client_id = "telegraf"

  data_format = "value"
  data_type = "float"
  [[inputs.mqtt_consumer.topic_parsing]]
   topic = "Simcofi/+/+/telemetry/+"
   measurement = "_/_/_/_/measurement"
   tags = "company/site/line/_/_"


[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "-7AfFpeinQ_RM-WCP2X-naHQrnq-rsgQ2XypH2nb96CmuGZh_-jjFOK-bnfKGe6u7E5x96FQmfH8ToEsm0InTA=="
  organization = "simcofi"
  bucket = "bucket0"


